### ISSUE TITLE
stoppped working

### ISSUE THREAD

**Issue by sdradsb** [Wolfrax/spots#1]
when I ran it for the first time, it ran perfect and got me the ADS-B signals. But when I stop it and ran it for the second time it stays blank.

Spots version 2.3.11
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Exact sample rate is: 2000000.052982 Hz

this is what happening when I run it for the second time. The program just exists. 

Would really appreciate if you could help me.

**Comment by Wolfrax** [comment]
This message comes from the underlying librtlsdr library, By experience, for me this implies that a process (likely spots) have not closed down correctly and is still holding the tuner device. The way to figure this out varies from OS.
On Linux, commands like "lsusb" or "usb-devices" will indicate if the device is connected to USB or not.
The easiest way is probably either 1) to logout/in on your system and retry, or 2) reboot your system.
Spots is listening to "signal.SIGTERM" and when receiving this (e.g. ctrl-C) _should_ close down correctly, and hence should be able to restart again. If you try to close won in other ways, the librtlsdr might still be connected to USB and block to open it again.

**Comment by nj0035** [comment]
Thank you for getting back to me. I will check this.
